### PR TITLE
Feature/config handling

### PR DESCRIPTION
**Pull request by hbj**

### CODE REVIEW

**Comment by janetbutts** [comment]
@jofomah , @freefony or @musamusa , does anyone know if this is still a valid request? can it be closed?

**Comment by musamusa** [comment]
@janetbutts I think it should be merged, it has taken care of some missing features required on the server side like dynamically adding host from Node environment and so on.  @freefony @jofomah any thought?

**Comment by janetbutts** [comment]
Any thoughts on @musamusa last comment @jofomah & @freefony ?

**Comment by freefony** [comment]
yeah i think it should

**Comment by tlvince** [comment]
Merging.

**Pull request merged**
