### PR TITLE
Refactor/restore facility stock count detail/history

### LINKED ISSUE #75: facilities page: add stock submission detail/history for each facility

### PR DESCRIPTION
**Pull request by musamusa**
Closes #75

### CODE REVIEW

**Comment by musamusa** [comment]
Closes #75

**Comment by janetbutts** [comment]
@jofomah , please review the pull request.

**Comment by jofomah** [comment]
@janetbutts  i don't even know what this ticket is supposed to do, so can't tell if it is done or not.

**Comment by janetbutts** [comment]
@jofomah, the purpose of this pull request should be to restore functionality on the facilities page. in the last dashboard release, users could click on the facility and see a table with the stock count history. that data was lost in the current release. so this will enable that functionality again.

**Comment by jofomah** [comment]
@janetbutts apart from few magic numbers used in the code and html templates look good to me.

Also when you say click on Facility Name it should show latest stock count, when i click on Facility name, it takes me to stock count page and show stock count but only for Test Facility, i clicked on other facilities and get no data even when they have last stock like 10 or 15 days ago. is that how it should work?

**Pull request closed without merging**
